#!/bin/bash

#SBATCH --job-name=pimc

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --time=12:00:00
#SBATCH --mem-per-cpu=4G

# Load the required modules and activate the conda environment.
source activate cpp_pimc

python main.py > out.out
conda deactivate